import {extractPdfText,parseRoster,fmt} from '../core/parser.js';import {Store} from '../core/storage.js';import {recoveryForJourneys} from '../core/operational-engine.js';import {trainingSuggestion} from '../core/health-engine.js';
export function renderSchedule(state){const data=state.imports[state.activeMonth];return `<div class="card"><h2>Escala IFN/iFlight Neo</h2>${monthButtons(state)}${data?summary(data):'<p class="sub">Nenhuma escala ativa.</p>'}</div><br>${data?tables(data):''}<br>${importer()}`}
function monthButtons(s){return `<div class="row">${Object.keys(s.imports).sort().map(m=>`<button class="btn ${m===s.activeMonth?'primary':''}" data-month="${m}">${m}</button>`).join('')}</div>`}
function summary(d){return `<div class="grid cards"><div><b>Dias</b><div class="metric">${d.summary.days}</div></div><div><b>Jornada</b><div class="metric">${d.summary.duty}h</div></div><div><b>Voo</b><div class="metric">${d.summary.flight}h</div></div><div><b>Folgas/VC</b><div class="metric">${d.summary.rests}</div></div></div>`}
function tables(data){const js=recoveryForJourneys(data.journeys).filter(j=>j.type!=='rest'&&j.type!=='vacation');return `<details open class="card"><summary><b>Jornadas do mês</b></summary><table class="table"><tr><th>Data</th><th>Jornada</th><th>Jornada</th><th>Voo</th><th>Eventos</th></tr>${js.map(j=>`<tr><td><b>${fmt.brDate(j.date)}</b></td><td>${j.label}<br><small class="sub">Apres. ${j.report||'—'} · Fim ${j.reg?.end||j.debrief||'—'}</small><br>${hotelPill(j)}</td><td>${j.dh}h</td><td>${j.fh}h</td><td>${j.events.map(e=>`<span class="pill flight" data-detail="${detail(e,j)}">${e.code}</span>`).join('')}</td></tr>`).join('')}</table></details><br><details class="card"><summary><b>Dias por treino recomendado</b></summary>${trainGroups(data.journeys)}</details>`}
function hotelPill(j){if(!j.recovery)return'';const c=j.recovery.status;return `<span class="pill ${c}" data-detail="Repouso oficial: ${j.recovery.official}h. Hotel estimado: ${j.recovery.hotelMin}–${j.recovery.hotelMax}h. Estimativa: chegada ao hotel entre 45–90 min após fim da jornada e saída 1h30–2h antes da decolagem/apresentação operacional. Confirme horários reais na operação.">Hotel ${j.recovery.hotelMin}–${j.recovery.hotelMax}h</span>`}
function detail(e,j){return `${e.code} ${e.depApt||''}-${e.arrApt||''}. Dep ${e.dep||'—'} Arr ${e.arr||'—'}. Apresentação da jornada ${j.report||'—'}; fim estimado ${j.reg?.end||j.debrief||'—'}.`}
function trainGroups(js){const g={};recoveryForJourneys(js).forEach(j=>{const k=trainingSuggestion(j);(g[k]??=[]).push(j)});return Object.entries(g).map(([k,v])=>`<p><b>${k}</b> · ${v.length} dia(s)<br>${v.map(j=>`<span class="pill">${fmt.brDate(j.date)}</span>`).join('')}</p>`).join('')}
function importer(){return `<div class="card"><h2>Importar escala</h2><input type="file" id="rosterFile" accept=".pdf,.txt"><label>Texto extraído/colado</label><textarea id="rosterText"></textarea><br><br><button class="btn primary" id="processRoster">Processar e salvar</button> <button class="btn danger" id="clearRoster">Limpar ativa</button><p class="sub" id="importMsg"></p></div>`}
export function bindSchedule(state){document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{state.activeMonth=b.dataset.month;Store.save(state);window.HealthOps.render('escala')});document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>window.HealthOps.modal('Detalhes',x.dataset.detail));const f=document.getElementById('rosterFile');if(f)f.onchange=async()=>{const file=f.files[0];if(!file)return;document.getElementById('importMsg').textContent='Lendo arquivo...';try{document.getElementById('rosterText').value=file.name.toLowerCase().endsWith('.pdf')?await extractPdfText(file):await file.text();document.getElementById('importMsg').textContent='Arquivo lido.'}catch(e){document.getElementById('importMsg').textContent='Falha na leitura: '+e.message}};const p=document.getElementById('processRoster');if(p)p.onclick=()=>{try{const parsed=parseRoster(document.getElementById('rosterText').value);state.imports[parsed.monthKey]=parsed;state.activeMonth=parsed.monthKey;Store.log(state,`Import ${parsed.monthKey}: ${parsed.journeys.length} jornadas`);window.HealthOps.render('escala')}catch(e){document.getElementById('importMsg').textContent=e.message;Store.log(state,e.stack)}};const c=document.getElementById('clearRoster');if(c)c.onclick=()=>{if(state.activeMonth)delete state.imports[state.activeMonth];state.activeMonth=Object.keys(state.imports).sort().at(-1)||null;Store.save(state);window.HealthOps.render('escala')}}
